"""Bytecode instruction definitions"""

PUSH = "PUSH"
POP = "POP"
DUP = "DUP"

LOAD = "LOAD"
STORE = "STORE"

ADD = "ADD"
SUB = "SUB"
MUL = "MUL"
DIV = "DIV"
MOD = "MOD"
POW = "POW"
FLOOR_DIV = "FLOOR_DIV"
NEG = "NEG"
NOT_OP = "NOT_OP"
AND = "AND"

EQ = "EQ"
NEQ = "NEQ"
LT = "LT"
GT = "GT"
LE = "LE"
GE = "GE"

JUMP = "JUMP"
JUMP_IF_FALSE = "JUMP_IF_FALSE"
JUMP_IF_TRUE = "JUMP_IF_TRUE"

CALL = "CALL"
CALL_METHOD = "CALL_METHOD"
RETURN = "RETURN"
MAKE_FUNC = "MAKE_FUNC"
STORE_METHOD = "STORE_METHOD"

MAKE_LIST = "MAKE_LIST"
MAKE_DICT = "MAKE_DICT"
INDEX = "INDEX"

GET_ATTR = "GET_ATTR"
SET_ATTR = "SET_ATTR"

HALT = "HALT"
LABEL = "LABEL"

# ── IR-level instructions (for optimization layer) ──
IR_LOAD_CONST = "IR_LOAD_CONST"
IR_ADD = "IR_ADD"
IR_SUB = "IR_SUB"
IR_MUL = "IR_MUL"
IR_DIV = "IR_DIV"
IR_STORE = "IR_STORE"
IR_LOAD = "IR_LOAD"
IR_JUMP_IF_FALSE = "IR_JUMP_IF_FALSE"
IR_CALL = "IR_CALL"
IR_RETURN = "IR_RETURN"